# Generated by Django 3.2.5 on 2023-05-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=255)),
                ('pdf', models.URLField(max_length=255)),
            ],
        ),
    ]
